DROP VIEW IF EXISTS address_balance_at_height;
DROP VIEW IF EXISTS address_balance;

DROP TABLE IF EXISTS input;
DROP TABLE IF EXISTS output;
DROP TABLE IF EXISTS tx;
DROP TABLE IF EXISTS block_tx;
DROP TABLE IF EXISTS block;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS indexer_state;
