name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_STAGING_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_STAGING_SA_KEY }}
          export_default_credentials: true

      - name: Install GCloud Components
        run: |
          # Needed for kubectl auth 
          # https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
          gcloud components install gke-gcloud-auth-plugin

      - name: Rollout
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          make image/build/staging
          make image/push/staging
          make k8s/rollout/staging
